name: Testing slack notification # Name of the workflow

on:                              # Defines when the workflow should run
  push:                          # Triggers the workflow whenever code is pushed
    branches:                    # Main Branch
      - main

jobs:                            # Jobs that will run in this workflow
  test-job:                      # ID of this job.
    runs-on: ubuntu-latest       # Environment for the job
    steps:                       # Lists actions to perform inside the job.
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show file content
        run: cat echo.txt
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"🚀 Slack notification: code pushed to main branch!"}' \
            $SLACK_WEBHOOK_URL